// Enums for Commodity
export enum Commodity {
  ADVERTISING_MATERIALS = "Advertising Materials/Books/Magazines",
  AGGREGATE = "Aggregate",
  AGRICULTURAL_MACHINERY = "Agricultural Machinery and Implements",
  AIR_CONDITIONING_PARTS = "Air Conditioning Equipment Parts",
  ALCOHOLIC_BEVERAGES = "Alcoholic Beverages/Beer/Wine/Spirits",
  ALUMINUM_PRODUCTS = "Aluminum Products",
  AUTOMOBILE_PARTS = "Automobile Parts",
  CHEMICALS = "Chemicals",
  CONSUMER_GOODS = "Consumer Goods",
  CONSTRUCTION_MATERIALS = "Construction Materials",
  ELECTRONICS = "Electronics",
  FROZEN_FOOD = "Frozen Food",
  FURNITURE = "Furniture",
  GRAIN = "Grain",
  HAZARDOUS_MATERIALS = "Hazardous Materials",
  MACHINERY = "Machinery",
  MEDICAL_SUPPLIES = "Medical Supplies",
  PAPER_PRODUCTS = "Paper Products",
  PERISHABLE_GOODS = "Perishable Goods",
  PETROLEUM_PRODUCTS = "Petroleum Products",
  PHARMACEUTICALS = "Pharmaceuticals",
  PLASTICS = "Plastics",
  RAW_MATERIALS = "Raw Materials",
  RECYCLABLES = "Recyclables",
  TEXTILES = "Textiles",
  VEHICLES = "Vehicles",
  WOOD_PRODUCTS = "Wood Products",
}
