// Enums for Load Option
export enum DispatchLoadType {
  SACKS_25LB = "25LB Sacks",
  CARTONS_40LB = "40LB Cartons",
  SACKS_50LB = "50LB Sacks",
  AIR_FREIGHT = "Air Freight",
  BACKHAUL = "Backhaul",
  BARRELS = "Barrels",
  BUSHEL = "Bushel",
  CUBIC_YARD = "Cubic Yard",
  CWT_100LB = "CWT/100LB",
  CWT_1LB = "CWT/1LB",
  CWT_TON = "CWT/Ton",
  DELIVERY = "Delivery",
  DIRECT = "Direct",
  DROP = "Drop",
  EQUIP_RENTAL_DAILY = "Equip. Rental - Daily",
  EQUIP_RENTAL_MONTHLY = "Equip. Rental - Monthly",
  EQUIP_RENTAL_WEEKLY = "Equip. Rental - Weekly",
  FEET = "Feet",
  FLATBED = "Flatbed",
  FULL_TRUCKLOAD = "Full Truckload",
  HOT_SHOT = "Hot Shot",
  HOURLY = "Hourly",
  KILOGRAMS = "Kilograms",
  LABOUR = "Labour",
  LBS = "LBS",
  LINE_HAUL = "Line Haul",
  LTL = "LTL",
  METRIC_TON = "Metric Ton",
  OCEAN = "Ocean",
  OTHER = "Other",
  PALLETS = "Pallets",
  PICK_UP = "Pick Up",
  PIECE = "Piece",
  PROFIT_SHARE = "Profit Share",
  RAIL = "Rail",
  RPM = "RPM",
  RPM_FSC = "RPM (FSC)",
  TONS = "Tons",
  TRUCK_ORDERED_NOT_USED = "Truck Ordered Not Used"
}

export const WithoutUnit = [
  "AIR_FREIGHT",
  "BACKHAUL",
  "DELIVERY",
  "DIRECT",
  "DROP",
  "FLATBED",
  "FULL_TRUCKLOAD",
  "HOT_SHOT",
  "LABOUR",
  "LINE_HAUL",
  "OCEAN",
  "OTHER",
  "PICK_UP",
  "PROFIT_SHARE",
  "RAIL",
  "TRUCK_ORDERED_NOT_USED"
];